# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from maum.brain.w2l import w2l_pb2 as maum_dot_brain_dot_w2l_dot_w2l__pb2


class SpeechToTextStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Recognize = channel.stream_unary(
                '/maum.brain.w2l.SpeechToText/Recognize',
                request_serializer=maum_dot_brain_dot_w2l_dot_w2l__pb2.Speech.SerializeToString,
                response_deserializer=maum_dot_brain_dot_w2l_dot_w2l__pb2.Text.FromString,
                )
        self.StreamRecognize = channel.stream_stream(
                '/maum.brain.w2l.SpeechToText/StreamRecognize',
                request_serializer=maum_dot_brain_dot_w2l_dot_w2l__pb2.Speech.SerializeToString,
                response_deserializer=maum_dot_brain_dot_w2l_dot_w2l__pb2.TextSegment.FromString,
                )


class SpeechToTextServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Recognize(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamRecognize(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SpeechToTextServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Recognize': grpc.stream_unary_rpc_method_handler(
                    servicer.Recognize,
                    request_deserializer=maum_dot_brain_dot_w2l_dot_w2l__pb2.Speech.FromString,
                    response_serializer=maum_dot_brain_dot_w2l_dot_w2l__pb2.Text.SerializeToString,
            ),
            'StreamRecognize': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamRecognize,
                    request_deserializer=maum_dot_brain_dot_w2l_dot_w2l__pb2.Speech.FromString,
                    response_serializer=maum_dot_brain_dot_w2l_dot_w2l__pb2.TextSegment.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'maum.brain.w2l.SpeechToText', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SpeechToText(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Recognize(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/maum.brain.w2l.SpeechToText/Recognize',
            maum_dot_brain_dot_w2l_dot_w2l__pb2.Speech.SerializeToString,
            maum_dot_brain_dot_w2l_dot_w2l__pb2.Text.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StreamRecognize(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/maum.brain.w2l.SpeechToText/StreamRecognize',
            maum_dot_brain_dot_w2l_dot_w2l__pb2.Speech.SerializeToString,
            maum_dot_brain_dot_w2l_dot_w2l__pb2.TextSegment.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
