# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: maum/brain/w2l/w2l.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18maum/brain/w2l/w2l.proto\x12\x0emaum.brain.w2l\"\x15\n\x06Speech\x12\x0b\n\x03\x62in\x18\x01 \x01(\x0c\"\x13\n\x04Text\x12\x0b\n\x03txt\x18\x01 \x01(\t\"6\n\x0bTextSegment\x12\r\n\x05start\x18\x01 \x01(\x05\x12\x0b\n\x03\x65nd\x18\x02 \x01(\x05\x12\x0b\n\x03txt\x18\x03 \x01(\t2\x97\x01\n\x0cSpeechToText\x12;\n\tRecognize\x12\x16.maum.brain.w2l.Speech\x1a\x14.maum.brain.w2l.Text(\x01\x12J\n\x0fStreamRecognize\x12\x16.maum.brain.w2l.Speech\x1a\x1b.maum.brain.w2l.TextSegment(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'maum.brain.w2l.w2l_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SPEECH']._serialized_start=44
  _globals['_SPEECH']._serialized_end=65
  _globals['_TEXT']._serialized_start=67
  _globals['_TEXT']._serialized_end=86
  _globals['_TEXTSEGMENT']._serialized_start=88
  _globals['_TEXTSEGMENT']._serialized_end=142
  _globals['_SPEECHTOTEXT']._serialized_start=145
  _globals['_SPEECHTOTEXT']._serialized_end=296
# @@protoc_insertion_point(module_scope)
